name: "GitHub Apps for GITHUB_TOKEN"

description: "Use GitHub Apps to create a new token and set it to an environment variable."

inputs:
  app-id:
    required: true
  private-key:
    required: true

runs:
  using: "composite"
  steps:
    - name: Generate GitHub Apps token
      id: GITHUB_TOKEN
      uses: tibdex/github-app-token@v1
      with:
        app_id: ${{ inputs.app-id }}
        private_key: ${{ inputs.private-key }}

    - run: |
        echo "APP_GITHUB_TOKEN=${{ steps.GITHUB_TOKEN.outputs.token }}" >> $GITHUB_ENV
      shell: bash

branding:
  icon: "box"
  color: "orange"